### ISSUE TITLE
Content has no field named 'owner'

### ISSUE THREAD

**Issue by oalders** [nickjj/ansible-fail2ban#4]
Via `ansible-galaxy install` (version is 2.6.1)

` [WARNING]: - nickjj/ansible-fail2ban was NOT installed successfully: Content has no
field named 'owner'`

**Comment by nickjj** [comment]
I would double check your requirements file.

I'm able to run `ansible-galaxy install nickjj.fail2ban` here.

```sh
nick@workstation:/tmp$ ansible-galaxy install nickjj.fail2ban
- downloading role 'fail2ban', owned by nickjj
- downloading role from https://github.com/nickjj/ansible-fail2ban/archive/v0.1.2.tar.gz
- extracting nickjj.fail2ban to /etc/ansible/roles/nickjj.fail2ban
- extracting nickjj.fail2ban to /e/src/github/nickjj.fail2ban
- nickjj.fail2ban (v0.1.2) was installed successfully
```

**Comment by TheNotary** [comment]
Hi, this issue should probably be closed, but I'm getting this error too.  

(requirements.yml)
```
dependencies:
  - geerlingguy.gitlab
```


```
$ ansible-galaxy install -r requirements.yml 
- downloading role 'dependencies', owned by 
 [WARNING]: - dependencies was NOT installed successfully: Content has no field named 'owner'

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

I'm assuming my `requirements.yml` is malformed.  
ansible-galaxy 2.5.4


*EDIT*

I solved my issue by just updating my requirements.yml to be like this:

(requirements.yml)
```
---
- src: geerlingguy.gitlab
```

**Comment by nickjj** [comment]
Hi, that seems unrelated to this role. This role doesn't depend on geerlingguy's gitlab role or any other role.

I'm able to run `ansible-galaxy install -p /tmp nickjj.fail2ban` which successfully downloads this role to `/tmp` (as a test).
